CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    avatar VARCHAR(500),
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    status INT NOT NULL DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS doc_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),
    sort_order INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS doc_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    file_name VARCHAR(500),
    file_path VARCHAR(500),
    file_size BIGINT DEFAULT 0,
    file_type VARCHAR(50),
    version INT DEFAULT 1,
    status VARCHAR(30) DEFAULT 'published',
    category_id BIGINT,
    creator_id BIGINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_doc_category FOREIGN KEY (category_id) REFERENCES doc_category(id),
    CONSTRAINT fk_doc_creator FOREIGN KEY (creator_id) REFERENCES sys_user(id)
);

CREATE TABLE IF NOT EXISTS doc_document_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version INT NOT NULL,
    file_name VARCHAR(500),
    file_path VARCHAR(500),
    file_size BIGINT DEFAULT 0,
    change_log VARCHAR(1000),
    uploader_id BIGINT NOT NULL,
    approval_status VARCHAR(30) DEFAULT 'approved',
    approval_record_id BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_version_document FOREIGN KEY (document_id) REFERENCES doc_document(id),
    CONSTRAINT fk_version_uploader FOREIGN KEY (uploader_id) REFERENCES sys_user(id)
);

CREATE TABLE IF NOT EXISTS doc_approval_flow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),
    status INT NOT NULL DEFAULT 1,
    creator_id BIGINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_flow_creator FOREIGN KEY (creator_id) REFERENCES sys_user(id)
);

CREATE TABLE IF NOT EXISTS doc_approval_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    approver_id BIGINT NOT NULL,
    node_order INT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_node_flow FOREIGN KEY (flow_id) REFERENCES doc_approval_flow(id),
    CONSTRAINT fk_node_approver FOREIGN KEY (approver_id) REFERENCES sys_user(id)
);

CREATE TABLE IF NOT EXISTS doc_approval_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    flow_id BIGINT NOT NULL,
    node_id BIGINT NOT NULL,
    approver_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    comment VARCHAR(1000),
    current_node_order INT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_record_document FOREIGN KEY (document_id) REFERENCES doc_document(id),
    CONSTRAINT fk_record_flow FOREIGN KEY (flow_id) REFERENCES doc_approval_flow(id),
    CONSTRAINT fk_record_node FOREIGN KEY (node_id) REFERENCES doc_approval_node(id),
    CONSTRAINT fk_record_approver FOREIGN KEY (approver_id) REFERENCES sys_user(id)
);
